config/routes.rb
Rantcat::Application.routes.draw do
  get "/posts", to: "posts#index", as: :home
  get "users/new"
  get "users/edit"
  get "users/show"
  get "sessions/new"
  get "sessions/create"
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signin', to: 'users#new', via: 'get'
  post 'users/show', to: 'posts#create', as: :user_posts
resources :users, except: [:destroy] do
  member do
    get :following, :follewers
  end
end

resources :posts, shallow: true do
  resources :posts
end
resources :sessions, except: [:destroy]

resources :friendships

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :userable, polymorphic: true
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :comment, presence: true
  validates_length_of :comment, maximum: 10000
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
belongs_to :parent, :class_name => "Post", :foreign_key => "post_id"
has_many :children, :class_name => "Post"

  validates :post, presence: true 
  validates_length_of :post, maximum: 10000 
end

app/models/user.rb
class User < ActiveRecord::Base
	

	has_many 	:friendships,
				dependent: :destroy,
				foreign_key: "follower_id"
	
	has_many	:reverse_friendships,
				dependent: :destroy,
				foreign_key: "followed_id",
				class_name: "Friendship"
	

	has_many 	:following,
				through: :friendships,
				source: :followed
	
	has_many	:followers,
				through: :reverse_friendships,
				source: :follower


	has_many 	:posts
	has_many 	:comments, as: :commentable
	validates 	:username, uniqueness: true, presence: true
	has_secure_password

	def follow!(followed)
		# relationships.create!(followed_id: followed.id)
		friendships.create!(followed_id: followed.id)
	end

	def following?(followed)
		friendships.find_by(followed_id: followed.id)
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
		@user = User.find(params[:friendship][:followed_id])
		current_user.follow!(@user)
		redirect_to :back
	end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # get root posts
  	@posts = Post.where(post_id: nil).order("created_at DESC")
    @post = Post.new
    # @comments = all_comments()
  end
  def show

  end

  def new
    # @post = Post.new
    # redirect_to :back
  end

  def create
    @user = current_user
    # render text: params
    if(params[:post_id].nil?)
      @post = Post.new(post_params)
      if @user.posts += [@post]
          # render text: current_user
        redirect_to :back #same thing as :posts_index
      else
        redirect_to :back
      end
    else
      @post = Post.find(params[:post_id]).children.build(post_params)
      if @post.save && @user.posts += [@post]
        redirect_to :back
      else
        redirect_to :back
      end
    end
  end

  def destroy
  end

  def update
  end



  # def createComment
  #   @comment = Post.new(post_params)
  #   @user = current_user
  #     if @user.posts += [@comment]
  #         # render text: current_user
  #       redirect_to :back #same thing as :posts_index
  #     else
  #       redirect_to :back
  #     end
  # end

private
  def post_params
    params.require(:post).permit(:post)
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	# def new
	# 	@ 
	# end
	def create
		# @creep = current_user.follow!(Post.user_id)
		@user = User.find(params[:friendship][:followed_id])
		current_user.follow!(@user)
		redirect_to :back
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user.new
	end
	def create
		user = User.find_by(username: params[:session][:username]).try(:authenticate, params[:session][:password])
		if user == false || user.nil?
	      redirect_to :back, flash: { message: "Incorrect email/password" }
	    else
	      sign_in(user)
	      redirect_to :posts
	    end
	  end
	def destroy
		sign_out
		redirect_to :home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def edit
  end

  def show
    @post = Post.new
  	@user = User.find(params[:id])
    @userposts = @user.posts

  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		sign_in(@user) 
  		redirect_to :posts
  	else
  		redirect_to :back
  	end
  end

  def update
  end

private
  def user_params
  	params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	# def all_comments(comments_array = [])
	# 	comments = Post.where(parent_id: :post_id)
	# 	comments_array += comments.all
	# 	comments.each do |comment|
	# 		comment.all_comments(comments_array)
	# 	end
	# 	comments_array
	# end


	# def test_print
	# 	content = []
	# 	# content << "<div>Fancy printy method</div>"
	# 	content << content_tag(:p, "Hello world!", class: "strong")
	# end

	def follow_button(user_to_follow)
		if signed_in? && !current_user.following?(user_to_follow)
			form_tag(friendships_path, method: :post, authenticity_token: true) do
				hidden_field_tag("friendship[followed_id]", user_to_follow.id.to_s) +
				button_tag(:submit, class: 'follow_butts') do
				  content_tag(:small, 'Follow')
				end
			end
		end
	end


	def comment_box(post)
		if signed_in?
			form_tag(posts_path, method: :post, authenticity_token: true, class: 'comment_form') do
				hidden_field_tag("post_id", post.id) +
				text_field_tag("post[post]") + 
				button_tag(:submit)
			end
		end
	end

	def show_comment_button
		if signed_in?
			button_tag(:Comment, class: 'show_comment')
		end
	end


	def print_tree(post, content, counter)
		counter += 1
		if content.nil?
			content = []
			temp_html = link_to(post.user.username, user_path(post.user), class: "username user"+post.user.id.to_s) + follow_button(post.user) + content_tag(:p, post.post, class: "root" ) + comment_box(post) + show_comment_button
			content << temp_html
		end
		if post.children.nil?
			return content
		else
			post.children.each_with_index do |child, index|
				temp_html = link_to(child.user.username, user_path(child.user), class: "user"+child.user.id.to_s) + content_tag(:p, child.post, class: "post"+counter.to_s ) + comment_box(child) + show_comment_button
					# + follow_button(child.user)
				content << temp_html
				print_tree(child, content, counter)
			end
		end
		return content
		puts "+++++++++++++++++++++++++++++++"
		puts content
		puts "+++++++++++++++++++++++++++++++"
	end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:user_id] = user.id
	end
	 def current_user= user
    	@current_user = user
  	end
  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	def signed_in?
	    !current_user.nil?
	end
	def sign_out
		session[:user_id] = nil
		self.current_user = nil
	end
	def current_user? user
	    user === current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rantcat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "posts", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="#">RANTCAT</a>
	      <div class="nav-collapse">
	        <ul class="nav">
		        <% if signed_in? %>	
		          <li><%= link_to "Sign out", signout_path, method: "delete" %> </li>
		          <li><%= link_to "Profile", user_path(current_user), method: "get" %></li>
		           <li><%= link_to "The Wall", home_path, method: "get" %></li>
		        <% else %>
		          <li><%= link_to "Sign in", signin_path, method: "get" %></li>
		        <% end %>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>

</body>
</html>

app/views/posts/index.html.erb
	<% if signed_in? %>
		<%= link_to "sign_out", signout_path, method: "delete" %> 
		<%= link_to "user", user_path(current_user), method: "get" %>
	<% else %>
		<%= link_to "sign_in", signin_path, method: "get" %>
	<% end %>

	<div class="mainbox">

		<p>MAIN POST BOX</p>

		<% if signed_in? %>
			<%= simple_form_for @post do |p| %>
				
				<%= p.input :post, label: false %>
				<%= p.button :submit, value: "Rant" %>
			<% end %>
		<% end %>
	</div>




	<% @posts.each do |post| %>
		<% print_tree(post, nil, 0).each do |a_post| %>
			<div class = "comments">
				<%= a_post %>
						<!-- <button>Comment</button> -->
			<!-- <p style="display: none">akdj;alkjdf;lkajd</p> -->
			


				

				<!--ADD IF STATEMENT FOR FOLLOW BUTTON -->
				<%# if signed_in? %>
				<%#= form_for(current_user.friendships.build(followed_id: post.user_id),
					             remote: true) do |f| %>
					<!-- <div> -->
						<%#= f.hidden_field :followed_id %>
						<%#= f.submit "Follow" %>
					<!-- </div> -->
				<%# end %>	
			</div>			
			<%# end %>		
		<% end %>



		<%# @posts.each do |comment| %> 
		<!-- <div class="comments"> -->

			<%# if post.id == comment.post_id %> <!-- compare the orginal post's id, with the comment(post)'s post_id -->
				<!-- <%#= comment.post %></br> -->
				<!-- <%#= comment.post_id %></br> -->
			<%# end %>
		<!-- </div> -->
		<%# end %>

	<% end %>
				<script>

					$(document).on("page:change", function(){
						$(".comment_form").hide();
						// $("button").click(function(){
						// 	$(this).next("p").toggle();
						// 	alert($(this).next("p").text());
						// 	// $("p").toggle();
						// });
					$(".show_comment").click(function(){
						$(this).prev(".comment_form").toggle();
					})
					})


				</script>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Hi, bitches. Rant away</h1>
<p>Register</p>


<%= simple_form_for @user do |formfield| %>
	<%= formfield.input :username, label: "Username:" %>
	<%= formfield.input :password, label: "Password:" %>
	<%= formfield.input :password_confirmation, label: "Confirm Password:" %>
	<%= formfield.button :submit %>
<% end %>	

<p>Login</p>
<%= simple_form_for(:session, url: sessions_path) do |f| %>
	<%= f.input :username, label: "Username:" %>
	<%= f.input :password, label: "Password:" %>
	<%= f.button :submit %>
<% end %>	
 

app/views/users/show.html.erb
<h1>User Profile</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p>Post</p>
	<% if current_user == @user %>
		<%= simple_form_for @post, url: posts_path do |p| %>
			<%= p.input :post, label: ""%>
			<%= p.button :submit %>
		<% end %>
	<% end %>

<% @userposts.each do |post| %>

<%= post.post %></br>

<% end %>

<%= link_to "sign_out", signout_path, method: "delete" %>